/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#include <unix_locks.h>
#include <sys/param.h>
#include <sys/systm.h>

#if	UNIX_LOCKS
#define	UPAR	1
#else
#define	UPAR	0
#endif

#include <sys/secdefines.h>

int	nosys();

int	nosys();
int	rexit();
int	fork();
int	read();
int	write();
int	close();
int	wait4();
int	link();
int	unlink();
int	execv();
int	chdir();
int	fchdir();
int	mknod();
int	chmod();
int	chown();
int	obreak();
int	getfsstat();
int	lseek();
int	getpid();
int	mount();
int	unmount();
int	setuid();
int	getuid();
int	exec_with_loader();
int	ptrace();
#ifdef	COMPAT_43
int	recvmsg();
int	sendmsg();
int	recvfrom();
int	accept();
int	getpeername();
int	getsockname();
#else
int	recvmsg();
int	sendmsg();
int	recvfrom();
int	accept();
int	getpeername();
int	getsockname();
#endif
int	saccess();
int	nosys();
int	nosys();
int	sync();
int	kill();
int	setpgid();
int	dup();
int	pipe();
int	set_program_attributes();
int	profil();
int	open();
int	getgid();
int	sigprocmask();
int	getlogin();
int	setlogin();
int	sysacct();
int	sigpending();
int	classcntl();
int	ioctl();
int	reboot();
int	revoke();
int	symlink();
int	readlink();
int	execve();
int	umask();
int	chroot();
int	getpgrp();
int	getpagesize();
int	mremap();
int	vfork();
int	stat();
int	lstat();
int	sbrk();
int	sstk();
int	smmap();
int	ovadvise();
int	munmap();
int	mprotect();
int	madvise();
int	kmodcall();
int	mincore();
int	getgroups();
int	setgroups();
int	setpgrp();
int	setitimer();
int	table();
int	getitimer();
int	gethostname();
int	sethostname();
int	getdtablesize();
int	dup2();
int	fstat();
int	fcntl();
int	select();
int	poll();
int	fsync();
int	setpriority();
int	socket();
int	connect();
#ifdef	COMPAT_43
int	oaccept();
#else
#endif
int	getpriority();
#ifdef	COMPAT_43
int	osend();
int	orecv();
#else
#endif
int	sigreturn();
int	bind();
int	setsockopt();
int	listen();
int	plock();
int	sigsuspend();
int	sigstack();
#ifdef	COMPAT_43
int	orecvmsg();
int	osendmsg();
#else
#endif
int	gettimeofday();
int	getrusage();
int	getsockopt();
int	readv();
int	writev();
int	settimeofday();
int	fchown();
int	fchmod();
#ifdef	COMPAT_43
int	orecvfrom();
#else
#endif
int	setreuid();
int	setregid();
int	rename();
int	truncate();
int	ftruncate();
int	flock();
int	setgid();
int	sendto();
int	shutdown();
int	socketpair();
int	mkdir();
int	rmdir();
int	utimes();
int	adjtime();
#ifdef	COMPAT_43
int	ogetpeername();
#else
#endif
int	gethostid();
int	sethostid();
int	getrlimit();
int	setrlimit();
int	setsid();
int	quotactl();
int	oldquota();
#ifdef	COMPAT_43
int	ogetsockname();
#else
#endif
int	pread();
int	pwrite();
int	pid_block();
int	pid_unblock();
int	signal_urti();
int	sigaction();
int	sigwaitprim();
int	nfssvc();
int	getdirentries();
int	statfs();
int	fstatfs();
int	async_daemon();
int	getfh();
int	getdomainname();
int	setdomainname();
int	exportfs();
int	getmnt();
int	swapon();
int	msgctl();
int	msgget();
int	msgrcv();
int	msgsnd();
int	semctl();
int	semget();
int	semop();
int	uname();
int	lchown();
int	shmat();
int	shmctl();
int	shmdt();
int	shmget();
int	mvalid();
int	getaddressconf();
int	msleep();
int	mwakeup();
int	msync();
int	ssig();
int	utc_gettime();
int	utc_adjtime();
int	security();
int	kloadcall();
int	getpgid();
int	getsid();
int	sigaltstack();
int	waitid();
int	priocntlset();
int	sigsendset();
int	set_speculative();
int	msfs_syscall();
int	sysinfo();
int	uadmin();
int	fuser();
int	proplist_syscall();
int	ntp_adjtime();
int	ntp_gettime();
int	pathconf();
int	fpathconf();
int	uswitch();
int	usleep_thread();
int	audcntl();
int	audgen();
int	sysfs();
int	subsys_info();
int	getsysinfo();
int	setsysinfo();
int	afs_syscall();
int	swapctl();
int	memcntl();
int	fdatasync();

#if COMPAT_43
#ifdef __STDC__
#define compat(n, name, c) n, 0+c, o##name
#define pcompat(n, name, c) n, 1+c, o##name
#define upcompat(n, name, c) n, UPAR+c, o##name

#else
#define compat(n, name, c) n, 0+c, o/**/name
#define pcompat(n, name, c) n, 1+c, o/**/name
#define upcompat(n, name, c) n, UPAR+c, o/**/name

#endif
int	oopen();
int	ocreat();
#ifdef	COMPAT_43
#else
#endif
int	ostat();
int	olstat();
int	ofstat();
int	ovhangup();
int	ogetpgrp();
int	owait();
#ifdef	COMPAT_43
#else
int	oaccept();
#endif
#ifdef	COMPAT_43
#else
int	osend();
int	orecv();
#endif
int	osigvec();
int	osigblock();
int	osigsetmask();
#ifdef	COMPAT_43
#else
int	orecvmsg();
int	osendmsg();
#endif
#ifdef	COMPAT_43
#else
int	orecvfrom();
#endif
#ifdef	COMPAT_43
#else
int	ogetpeername();
#endif
int	okillpg();
#ifdef	COMPAT_43
#else
int	ogetsockname();
#endif

#else /* COMPAT_43 */
#define compat(n, name, c) 0, 0+c, nosys
#define pcompat(n, name, c) 0, 1+c, nosys
#define upcompat(n, name, c) 0, UPAR+c, nosys
#endif /* COMPAT_43 */

struct sysent sysent[] = {
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 0 = syscall */
	1, 1, rexit,	{'0','0','0','0','0','0','4'},		/* 1 = exit */
	0, 1, fork,	{'0','0','0','0','0','0','0'},		/* 2 = fork */
	3, 3, read,	{'c','0','0','0','0','0','1'},		/* 3 = read */
	3, 3, write,	{'c','0','0','0','0','0','0'},		/* 4 = write */
	pcompat(3,open,2),	{'W','a','2','0','0','0','1'},	/* 5 = old open */
	1, 3, close,	{'C','0','0','0','0','0','5'},		/* 6 = close */
	4, 3, wait4,	{'0','0','0','0','0','0','0'},		/* 7 = wait4 */
	pcompat(2,creat,2),	{'W','2','0','0','0','0','0'},	/* 8 = old creat */
	2, 1, link,	{'B','B','0','0','0','0','1'},		/* 9 = link */
	1, 1, unlink,	{'B','0','0','0','0','0','0'},		/* 10 = unlink */
	2, 1, execv,	{'R','r','0','0','0','0','7'},		/* 11 = execv */
	1, 1, chdir,	{'b','0','0','0','0','0','0'},		/* 12 = chdir */
	1, 1, fchdir,	{'c','0','0','0','0','0','0'},		/* 13 = fchdir */
	3, 1, mknod,	{'X','2','0','0','0','0','0'},		/* 14 = mknod */
	2, 1, chmod,	{'B','2','0','0','0','0','0'},		/* 15 = chmod */
	3, 1, chown,	{'B','l','m','0','0','0','0'},		/* 16 = chown */
	1, 1, obreak,	{'3','0','0','0','0','0','0'},		/* 17 = obreak */
	3, 1, getfsstat,	{'0','0','0','0','0','0','0'},		/* 18 = getfsstat */
	3, 3, lseek,	{'0','0','0','0','0','0','1'},		/* 19 = lseek */
	0, 1, getpid,	{'0','0','0','0','0','0','0'},		/* 20 = getpid */
	4, 1, mount,	{'0','0','0','0','0','0','4'},		/* 21 = mount */
	2, 1, unmount,	{'B','a','0','0','0','0','0'},		/* 22 = unmount */
	1, 1, setuid,	{'l','0','0','0','0','0','0'},		/* 23 = setuid */
	0, 1, getuid,	{'0','0','0','0','0','0','0'},		/* 24 = getuid */
	5, 1, exec_with_loader,	{'R','r','r','r','0','0','7'},		/* 25 = exec_with_loader */
	4, 1, ptrace,	{'a','Q','0','0','0','0','0'},		/* 26 = ptrace */
#ifdef	COMPAT_43
	3, 3, recvmsg,	{'c','T','0','0','0','0','0'},		/* 27 = nrecvmsg */
	3, 3, sendmsg,	{'c','T','0','0','0','0','0'},		/* 28 = nsendmsg */
	6, 3, recvfrom,	{'c','0','0','0','0','0','0'},		/* 29 = nrecvfrom */
	3, 3, accept,	{'c','0','0','0','0','0','0'},		/* 30 = naccept */
	3, 1, getpeername,	{'0','0','0','0','0','0','0'},		/* 31 = ngetpeername */
	3, 1, getsockname,	{'0','0','0','0','0','0','0'},		/* 32 = ngetsockname */
#else
	3, 3, recvmsg,	{'c','T','0','0','0','0','0'},		/* 27 = recvmsg */
	3, 3, sendmsg,	{'c','T','0','0','0','0','0'},		/* 28 = sendmsg */
	6, 3, recvfrom,	{'c','0','0','0','0','0','0'},		/* 29 = recvfrom */
	3, 3, accept,	{'c','0','0','0','0','0','0'},		/* 30 = accept */
	3, 1, getpeername,	{'0','0','0','0','0','0','0'},		/* 31 = getpeername */
	3, 1, getsockname,	{'0','0','0','0','0','0','0'},		/* 32 = getsockname */
#endif
	2, 1, saccess,	{'B','0','0','0','0','0','1'},		/* 33 = access */
	2, 1, nosys,	{'B','a','0','0','0','0','0'},		/* 34 = chflags */
	2, 1, nosys,	{'c','a','0','0','0','0','0'},		/* 35 = fchflags */
	0, 1, sync,	{'0','0','0','0','0','0','0'},		/* 36 = sync */
	2, 1, kill,	{'Q','a','0','0','0','0','0'},		/* 37 = kill */
	pcompat(2,stat,0),	{'B','0','0','0','0','0','1'},	/* 38 = old stat */
	2, 1, setpgid,	{'Q','a','0','0','0','0','0'},		/* 39 = setpgid */
	pcompat(2,lstat,0),	{'B','0','0','0','0','0','1'},	/* 40 = old lstat */
	2, 1, dup,	{'C','0','0','0','0','0','1'},		/* 41 = dup */
	0, 1, pipe,	{'0','0','0','0','0','0','4'},		/* 42 = pipe */
	4, 1, set_program_attributes,	{'0','0','0','0','0','0','0'},		/* 43 = set_program_attributes */
	4, 1, profil,	{'0','0','0','0','0','0','0'},		/* 44 = profil */
	3, 3, open,	{'W','a','2','0','0','0','1'},		/* 45 = open */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 46 = obsolete osigaction */
	0, 1, getgid,	{'0','0','0','0','0','0','0'},		/* 47 = getgid */
	2, 1, sigprocmask,	{'0','0','0','0','0','0','0'},		/* 48 = sigprocmask */
	2, 1, getlogin,	{'0','0','0','0','0','0','0'},		/* 49 = getlogin */
	2, 1, setlogin,	{'b','0','0','0','0','0','0'},		/* 50 = setlogin */
	1, 1, sysacct,	{'b','0','0','0','0','0','0'},		/* 51 = acct */
	0, 1, sigpending,	{'0','0','0','0','0','0','0'},		/* 52 = sigpending */
	4, 1, classcntl,	{'a','0','0','0','0','0','0'},		/* 53 = classcntl */
	3, 3, ioctl,	{'C','3','0','0','0','0','4'},		/* 54 = ioctl */
	1, 0, reboot,	{'0','0','0','0','0','0','4'},		/* 55 = reboot */
	1, 0, revoke,	{'B','0','0','0','0','0','1'},		/* 56 = revoke */
	2, 1, symlink,	{'B','B','0','0','0','0','0'},		/* 57 = symlink */
	3, 1, readlink,	{'B','0','0','0','0','0','1'},		/* 58 = readlink */
	3, 1, execve,	{'R','r','r','0','0','0','7'},		/* 59 = execve */
	1, 1, umask,	{'0','0','0','0','0','0','0'},		/* 60 = umask */
	1, 1, chroot,	{'b','0','0','0','0','0','0'},		/* 61 = chroot */
	pcompat(2,fstat,0),	{'c','0','0','0','0','0','1'},	/* 62 = old fstat */
	0, 1, getpgrp,	{'0','0','0','0','0','0','0'},		/* 63 = getpgrp */
	1, 1, getpagesize,	{'0','0','0','0','0','0','0'},		/* 64 = getpagesize */
	5, 1, mremap,	{'0','0','0','0','0','0','0'},		/* 65 = mremap */
	0, 1, vfork,	{'0','0','0','0','0','0','0'},		/* 66 = vfork */
	2, 1, stat,	{'B','0','0','0','0','0','1'},		/* 67 = stat */
	2, 1, lstat,	{'B','0','0','0','0','0','1'},		/* 68 = lstat */
	1, 1, sbrk,	{'0','0','0','0','0','0','0'},		/* 69 = sbrk */
	1, 1, sstk,	{'0','0','0','0','0','0','0'},		/* 70 = sstk */
	6, 1, smmap,	{'3','3','a','a','c','0','0'},		/* 71 = mmap */
	1, 0, ovadvise,	{'0','0','0','0','0','0','0'},		/* 72 = ovadvise */
	2, 1, munmap,	{'3','3','0','0','0','0','0'},		/* 73 = munmap */
	3, 1, mprotect,	{'3','3','a','0','0','0','0'},		/* 74 = mprotect */
	3, 1, madvise,	{'0','0','0','0','0','0','0'},		/* 75 = madvise */
	compat(1,vhangup,0),	{'0','0','0','0','0','0','0'},	/* 76 = old vhangup */
	6, 1, kmodcall,	{'b','a','0','0','0','0','0'},		/* 77 = kmodcall */
	3, 1, mincore,	{'0','0','0','0','0','0','0'},		/* 78 = mincore */
	2, 1, getgroups,	{'0','0','0','0','0','0','0'},		/* 79 = getgroups */
	2, 1, setgroups,	{'0','5','0','0','0','0','0'},		/* 80 = setgroups */
	pcompat(1,getpgrp,0),	{'0','0','0','0','0','0','0'},	/* 81 = old getpgrp */
	2, 1, setpgrp,	{'Q','a','0','0','0','0','0'},		/* 82 = setpgrp */
	3, 1, setitimer,	{'0','0','0','0','0','0','0'},		/* 83 = setitimer */
	pcompat(3,wait,2),	{'0','0','0','0','0','0','0'},	/* 84 = old wait */
	5, 1, table,	{'a','a','0','a','0','0','0'},		/* 85 = table */
	2, 1, getitimer,	{'0','0','0','0','0','0','0'},		/* 86 = getitimer */
	2, 3, gethostname,	{'0','0','0','0','0','0','0'},		/* 87 = gethostname */
	2, 1, sethostname,	{'g','0','0','0','0','0','0'},		/* 88 = sethostname */
	0, 1, getdtablesize,	{'0','0','0','0','0','0','0'},		/* 89 = getdtablesize */
	2, 1, dup2,	{'C','C','0','0','0','0','5'},		/* 90 = dup2 */
	2, 1, fstat,	{'c','0','0','0','0','0','1'},		/* 91 = fstat */
	3, 3, fcntl,	{'C','a','0','0','0','0','4'},		/* 92 = fcntl */
	5, 3, select,	{'0','0','0','0','0','0','0'},		/* 93 = select */
	3, 3, poll,	{'0','0','0','0','0','0','0'},		/* 94 = poll */
	1, 3, fsync,	{'0','0','0','0','0','0','0'},		/* 95 = fsync */
	3, 1, setpriority,	{'a','a','0','0','0','0','0'},		/* 96 = setpriority */
	3, 1, socket,	{'a','a','a','0','0','0','0'},		/* 97 = socket */
	3, 3, connect,	{'c','H','0','0','0','0','0'},		/* 98 = connect */
#ifdef	COMPAT_43
	3, 3, oaccept,	{'c','0','0','0','0','0','0'},		/* 99 = accept */
#else
	pcompat(3,accept,2),	{'c','0','0','0','0','0','0'},	/* 99 = old accept */
#endif
	2, 1, getpriority,	{'0','0','0','0','0','0','0'},		/* 100 = getpriority */
#ifdef	COMPAT_43
	4, 3, osend,	{'c','0','0','0','0','0','0'},		/* 101 = send */
	4, 3, orecv,	{'c','0','0','0','0','0','0'},		/* 102 = recv */
#else
	pcompat(4,send,2),	{'c','0','0','0','0','0','0'},	/* 101 = old send */
	pcompat(4,recv,2),	{'c','0','0','0','0','0','0'},	/* 102 = old recv */
#endif
	1, 1, sigreturn,	{'0','0','0','0','0','0','0'},		/* 103 = sigreturn */
	3, 1, bind,	{'c','H','0','0','0','0','0'},		/* 104 = bind */
	5, 1, setsockopt,	{'c','a','a','0','0','0','0'},		/* 105 = setsockopt */
	2, 1, listen,	{'0','0','0','0','0','0','0'},		/* 106 = listen */
	1, 1, plock,	{'0','0','0','0','0','0','0'},		/* 107 = plock */
	pcompat(4,sigvec,0),	{'0','0','0','0','0','0','0'},	/* 108 = old sigvec */
	pcompat(1,sigblock,0),	{'0','0','0','0','0','0','0'},	/* 109 = old sigblock */
	pcompat(1,sigsetmask,0),	{'0','0','0','0','0','0','0'},	/* 110 = old sigsetmask */
	1, 3, sigsuspend,	{'0','0','0','0','0','0','0'},		/* 111 = sigsuspend */
	2, 1, sigstack,	{'0','0','0','0','0','0','0'},		/* 112 = sigstack */
#ifdef	COMPAT_43
	3, 3, orecvmsg,	{'c','I','0','0','0','0','0'},		/* 113 = recvmsg */
	3, 3, osendmsg,	{'c','I','0','0','0','0','0'},		/* 114 = sendmsg */
#else
	pcompat(3,recvmsg,2),	{'c','T','0','0','0','0','0'},	/* 113 = old recvmsg */
	pcompat(3,sendmsg,2),	{'c','T','0','0','0','0','0'},	/* 114 = old sendmsg */
#endif
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 115 = obsolete vtrace */
	2, 1, gettimeofday,	{'0','0','0','0','0','0','0'},		/* 116 = gettimeofday */
	2, 1, getrusage,	{'0','0','0','0','0','0','0'},		/* 117 = getrusage */
	5, 1, getsockopt,	{'0','0','0','0','0','0','0'},		/* 118 = getsockopt */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 119 = nosys */
	3, 3, readv,	{'c','0','0','0','0','0','1'},		/* 120 = readv */
	3, 3, writev,	{'c','0','0','0','0','0','0'},		/* 121 = writev */
	2, 1, settimeofday,	{'0','0','0','0','0','0','0'},		/* 122 = settimeofday */
	3, 1, fchown,	{'C','l','m','0','0','0','0'},		/* 123 = fchown */
	2, 1, fchmod,	{'C','2','0','0','0','0','0'},		/* 124 = fchmod */
#ifdef	COMPAT_43
	6, 3, orecvfrom,	{'c','0','0','0','0','0','0'},		/* 125 = recvfrom */
#else
	pcompat(6,recvfrom,2),	{'c','0','0','0','0','0','0'},	/* 125 = old recvfrom */
#endif
	2, 1, setreuid,	{'a','a','0','0','0','0','0'},		/* 126 = setreuid */
	2, 1, setregid,	{'a','a','0','0','0','0','0'},		/* 127 = setregid */
	2, 3, rename,	{'B','B','0','0','0','0','0'},		/* 128 = rename */
	2, 1, truncate,	{'B','0','0','0','0','0','0'},		/* 129 = truncate */
	2, 1, ftruncate,	{'C','0','0','0','0','0','0'},		/* 130 = ftruncate */
	2, 1, flock,	{'0','0','0','0','0','0','0'},		/* 131 = flock */
	1, 1, setgid,	{'m','0','0','0','0','0','0'},		/* 132 = setgid */
	6, 3, sendto,	{'c','0','0','0','H','0','0'},		/* 133 = sendto */
	2, 1, shutdown,	{'c','a','0','0','0','0','0'},		/* 134 = shutdown */
	4, 1, socketpair,	{'0','0','0','s','0','0','0'},		/* 135 = socketpair */
	2, 1, mkdir,	{'X','2','0','0','0','0','0'},		/* 136 = mkdir */
	1, 1, rmdir,	{'B','0','0','0','0','0','0'},		/* 137 = rmdir */
	2, 1, utimes,	{'B','0','0','0','0','0','0'},		/* 138 = utimes */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 139 = obsolete 4.2 sigreturn */
	2, 1, adjtime,	{'0','0','0','0','0','0','0'},		/* 140 = adjtime */
#ifdef	COMPAT_43
	3, 1, ogetpeername,	{'0','0','0','0','0','0','0'},		/* 141 = getpeername */
#else
	pcompat(3,getpeername,0),	{'0','0','0','0','0','0','0'},	/* 141 = old getpeername */
#endif
	0, 1, gethostid,	{'0','0','0','0','0','0','0'},		/* 142 = gethostid */
	1, 1, sethostid,	{'a','0','0','0','0','0','0'},		/* 143 = sethostid */
	2, 1, getrlimit,	{'0','0','0','0','0','0','0'},		/* 144 = getrlimit */
	2, 1, setrlimit,	{'0','0','0','0','0','0','0'},		/* 145 = setrlimit */
	pcompat(2,killpg,0),	{'a','a','0','0','0','0','0'},	/* 146 = old killpg */
	0, 1, setsid,	{'0','0','0','0','0','0','0'},		/* 147 = setsid */
	4, 1, quotactl,	{'0','0','0','0','0','0','0'},		/* 148 = quotactl */
	4, 1, oldquota,	{'0','0','0','0','0','0','0'},		/* 149 = oldquota */
#ifdef	COMPAT_43
	3, 1, ogetsockname,	{'0','0','0','0','0','0','0'},		/* 150 = getsockname */
#else
	pcompat(3,getsockname,0),	{'0','0','0','0','0','0','0'},	/* 150 = old getsockname */
#endif
	4, 3, pread,	{'c','0','0','0','0','0','1'},		/* 151 = pread */
	4, 3, pwrite,	{'c','0','0','0','0','0','0'},		/* 152 = pwrite */
	2, 1, pid_block,	{'0','0','0','0','0','0','0'},		/* 153 = pid_block */
	2, 1, pid_unblock,	{'Q','a','0','0','0','0','0'},		/* 154 = pid_unblock */
	2, 1, signal_urti,	{'0','0','0','0','0','0','0'},		/* 155 = signal_urti */
	4, 1, sigaction,	{'0','0','0','0','0','0','0'},		/* 156 = sigaction */
	3, 3, sigwaitprim,	{'0','0','0','0','0','0','0'},		/* 157 = sigwaitprim */
	4, 1, nfssvc,	{'0','0','0','0','0','0','0'},		/* 158 = nfssvc */
	4, 1, getdirentries,	{'c','0','0','0','0','0','1'},		/* 159 = getdirentries */
	2, 1, statfs,	{'b','0','0','0','0','0','0'},		/* 160 = statfs */
	2, 1, fstatfs,	{'c','0','0','0','0','0','0'},		/* 161 = fstatfs */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 162 = nosys */
	2, 1, async_daemon,	{'0','0','0','0','0','0','0'},		/* 163 = async_daemon */
	3, 1, getfh,	{'0','0','0','0','0','0','0'},		/* 164 = getfh */
	2, 1, getdomainname,	{'0','0','0','0','0','0','0'},		/* 165 = getdomainname */
	2, 1, setdomainname,	{'g','0','0','0','0','0','0'},		/* 166 = setdomainname */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 167 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 168 = nosys */
	3, 0, exportfs,	{'a','4','v','0','0','0','0'},		/* 169 = exportfs */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 170 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 171 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 172 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 173 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 174 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 175 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 176 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 177 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 178 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 179 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 180 = nosys */
	1, 1, plock,	{'0','0','0','0','0','0','0'},		/* 181 = plock (alternate) */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 182 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 183 = nosys */
	5, 0, getmnt,	{'0','0','0','0','0','0','0'},		/* 184 = getmnt */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 185 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 186 = nosys */
	1, 1, sigpending,	{'0','0','0','0','0','0','0'},		/* 187 = sigpending (alternate) */
	0, 1, setsid,	{'0','0','0','0','0','0','0'},		/* 188 = setsid (alternate) */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 189 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 190 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 191 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 192 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 193 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 194 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 195 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 196 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 197 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 198 = nosys */
	4, 1, swapon,	{'B','a','3','3','0','0','0'},		/* 199 = swapon */
	3, 1, msgctl,	{'A','a','K','0','0','0','0'},		/* 200 = msgctl */
	2, 1, msgget,	{'A','a','0','0','0','0','0'},		/* 201 = msgget */
	5, 3, msgrcv,	{'A','0','0','0','0','0','0'},		/* 202 = msgrcv */
	4, 3, msgsnd,	{'A','0','0','0','0','0','0'},		/* 203 = msgsnd */
	4, 1, semctl,	{'A','0','a','n','0','0','0'},		/* 204 = semctl */
	3, 1, semget,	{'A','0','a','0','0','0','0'},		/* 205 = semget */
	3, 3, semop,	{'A','0','0','0','0','0','0'},		/* 206 = semop */
	1, 1, uname,	{'0','0','0','0','0','0','0'},		/* 207 = uname */
	3, 1, lchown,	{'B','l','m','0','0','0','0'},		/* 208 = lchown */
	3, 1, shmat,	{'A','0','a','0','0','0','0'},		/* 209 = shmat */
	3, 1, shmctl,	{'A','a','o','0','0','0','0'},		/* 210 = shmctl */
	1, 1, shmdt,	{'3','0','0','0','0','0','0'},		/* 211 = shmdt */
	3, 1, shmget,	{'A','0','a','0','0','0','0'},		/* 212 = shmget */
	3, 1, mvalid,	{'0','0','0','0','0','0','0'},		/* 213 = mvalid */
	2, 1, getaddressconf,	{'0','0','0','0','0','0','0'},		/* 214 = getaddressconf */
	1, 3, msleep,	{'0','0','0','0','0','0','0'},		/* 215 = msleep */
	1, 1, mwakeup,	{'0','0','0','0','0','0','0'},		/* 216 = mwakeup */
	3, 3, msync,	{'0','0','0','0','0','0','0'},		/* 217 = msync */
	3, 1, ssig,	{'0','0','0','0','0','0','0'},		/* 218 = signal */
	1, 1, utc_gettime,	{'0','0','0','0','0','0','0'},		/* 219 = utc_gettime */
	2, 1, utc_adjtime,	{'a','0','0','0','0','0','0'},		/* 220 = utc_adjtime */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 221 = nosys */
	6, 1, security,	{'0','0','0','0','0','0','4'},		/* 222 = security */
	5, 0, kloadcall,	{'a','3','3','3','3','0','0'},		/* 223 = kloadcall */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 224 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 225 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 226 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 227 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 228 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 229 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 230 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 231 = nosys */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 232 = nosys */
	1, 1, getpgid,	{'0','0','0','0','0','0','0'},		/* 233 = getpgid */
	1, 1, getsid,	{'0','0','0','0','0','0','0'},		/* 234 = getsid */
	3, 1, sigaltstack,	{'0','0','0','0','0','0','0'},		/* 235 = sigaltstack */
	4, 3, waitid,	{'0','0','0','0','0','0','0'},		/* 236 = waitid */
	3, 1, priocntlset,	{'0','0','0','0','0','0','4'},		/* 237 = priocntlset */
	2, 1, sigsendset,	{'0','0','0','0','0','0','4'},		/* 238 = sigsendset */
	5, 1, set_speculative,	{'0','0','0','0','0','0','0'},		/* 239 = set_speculative */
	3, 1, msfs_syscall,	{'0','0','0','0','0','0','4'},		/* 240 = msfs_syscall */
	3, 1, sysinfo,	{'a','g','0','0','0','0','0'},		/* 241 = sysinfo */
	3, 0, uadmin,	{'0','0','0','0','0','0','4'},		/* 242 = uadmin */
	4, 1, fuser,	{'B','0','0','0','0','0','0'},		/* 243 = fuser */
	2, 1, proplist_syscall,	{'0','0','0','0','0','0','4'},		/* 244 = proplist_syscall */
	1, 0, ntp_adjtime,	{'0','0','0','0','0','0','0'},		/* 245 = ntp_adjtime */
	1, 0, ntp_gettime,	{'0','0','0','0','0','0','0'},		/* 246 = ntp_gettime */
	2, 1, pathconf,	{'b','a','0','0','0','0','0'},		/* 247 = pathconf */
	2, 1, fpathconf,	{'c','a','0','0','0','0','0'},		/* 248 = fpathconf */
	0, 1, nosys,	{'0','0','0','0','0','0','0'},		/* 249 = nosys */
	3, 1, uswitch,	{'0','0','0','0','0','0','0'},		/* 250 = uswitch */
	2, 3, usleep_thread,	{'0','0','0','0','0','0','0'},		/* 251 = usleep_thread */
	6, 1, audcntl,	{'a','g','0','a','a','q','4'},		/* 252 = audcntl */
	5, 1, audgen,	{'0','0','0','0','0','0','0'},		/* 253 = audgen */
	3, 1, sysfs,	{'0','0','0','0','0','0','0'},		/* 254 = sysfs */
	2, 1, subsys_info,	{'0','0','0','0','0','0','0'},		/* 255 = subsys_info */
	6, 1, getsysinfo,	{'0','0','0','0','0','0','0'},		/* 256 = getsysinfo */
	5, 1, setsysinfo,	{'a','0','0','0','0','0','0'},		/* 257 = setsysinfo */
	6, 0, afs_syscall,	{'0','0','0','0','0','0','0'},		/* 258 = afs_syscall */
	2, 1, swapctl,	{'0','0','0','0','0','0','4'},		/* 259 = swapctl */
	6, 1, memcntl,	{'3','3','a','a','a','a','0'},		/* 260 = memcntl */
	1, 3, fdatasync,	{'0','0','0','0','0','0','0'},		/* 261 = fdatasync */
};

int	nsysent = sizeof(sysent) / sizeof(sysent[0]);
