/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from;
 */

char *rt_syscallnames[] = {
	"memlk",			/* 0 = memlk */
	"memunlk",			/* 1 = memunlk */
	"psx4_get_todtimer",			/* 2 = psx4_get_todtimer */
	"psx4_set_todtimer",			/* 3 = psx4_set_todtimer */
	"psx4_time_drift",			/* 4 = psx4_time_drift */
	"rt_getprio",			/* 5 = rt_getprio */
	"rt_setprio",			/* 6 = rt_setprio */
	"psx4_timer_create",			/* 7 = psx4_timer_create */
	"psx4_timer_delete",			/* 8 = psx4_timer_delete */
	"psx4_sem_sleep",			/* 9 = psx4_sem_sleep */
	"psx4_sem_wakeup",			/* 10 = psx4_sem_wakeup */
	"aio_init",			/* 11 = aio_init */
	"aio_transfer_old",			/* 12 = aio_transfer_old */
	"aio_transfer_done",			/* 13 = aio_transfer_done */
	"obs aio_wait_d11",			/* 14 = obsolete aio_wait_d11 */
	"aio_done",			/* 15 = aio_done */
	"aio_transfer_cancel",			/* 16 = aio_transfer_cancel */
	"aio_info",			/* 17 = aio_info */
	"psx4_ipc_snd_sleep",			/* 18 = psx4_ipc_snd_sleep */
	"psx4_ipc_rcv_sleep",			/* 19 = psx4_ipc_rcv_sleep */
	"psx4_ipc_wakeup_sender",			/* 20 = psx4_ipc_wakeup_sender */
	"psx4_ipc_wakeup_receiver",			/* 21 = psx4_ipc_wakeup_receiver */
	"psx4_csem_sleep_wakeup",			/* 22 = psx4_csem_sleep_wakeup */
	"aio_wait",			/* 23 = aio_wait */
	"aioinit_lock_sleep",			/* 24 = aioinit_lock_sleep */
	"aioinit_lock_wakeup",			/* 25 = aioinit_lock_wakeup */
	"psx4_ipc_notify",			/* 26 = psx4_ipc_notify */
	"psx4_sigqueue",			/* 27 = psx4_sigqueue */
	"psx4_timer_overrun",			/* 28 = psx4_timer_overrun */
	"aio_transfer",			/* 29 = aio_transfer */
	"aio_group_init",			/* 30 = aio_group_init */
	"aio_group_info",			/* 31 = aio_group_info */
};
