/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#include <unix_locks.h>
#include <sys/param.h>
#include <sys/systm.h>

#if	UNIX_LOCKS
#define	UPAR	1
#else
#define	UPAR	0
#endif

#include <sys/secdefines.h>

int	nosys();

int	sysv_unlink();
int	sysv_open();
int	sysv_waitpid();

#if COMPAT_43
#ifdef __STDC__
#define compat(n, name, c) n, 0+c, o##name
#define pcompat(n, name, c) n, 1+c, o##name
#define upcompat(n, name, c) n, UPAR+c, o##name

#else
#define compat(n, name, c) n, 0+c, o/**/name
#define pcompat(n, name, c) n, 1+c, o/**/name
#define upcompat(n, name, c) n, UPAR+c, o/**/name

#endif

#else /* COMPAT_43 */
#define compat(n, name, c) 0, 0+c, nosys
#define pcompat(n, name, c) 0, 1+c, nosys
#define upcompat(n, name, c) 0, UPAR+c, nosys
#endif /* COMPAT_43 */

struct sysent sysv_sysent[] = {
	1, 3, sysv_unlink,	{'B','0','0','0','0','0','0'},		/* 0 = unlink */
	3, 3, sysv_open,	{'W','a','1','0','0','0','1'},		/* 1 = open */
	3, 3, sysv_waitpid,	{'0','0','0','0','0','0','0'},		/* 2 = waitpid */
};

int	sysv_nsysent = sizeof(sysv_sysent) / sizeof(sysv_sysent[0]);
