/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

char *sysv_syscallnames[] = {
	"unlink",			/* 0 = unlink */
	"open",			/* 1 = open */
	"waitpid",			/* 2 = waitpid */
};
