/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef	_SYS_ULT_SYSCALL_H_
#define	_SYS_ULT_SYSCALL_H_

#define	SYS_ult_syscall	0
#define	SYS_ult_exit	1
#define	SYS_ult_fork	2
#define	SYS_ult_read	3
#define	SYS_ult_write	4
#define	SYS_ult_open	5
#define	SYS_ult_close	6
				/* 7 is obsolete wait */
#define	SYS_ult_creat	8
#define	SYS_ult_link	9
#define	SYS_ult_unlink	10
#define	SYS_ult_execv	11
#define	SYS_ult_chdir	12
				/* 13 is obsolete time */
#define	SYS_ult_mknod	14
#define	SYS_ult_chmod	15
#define	SYS_ult_chown	16
#define	SYS_ult_obreak	17
				/* 18 is obsolete stat */
#define	SYS_ult_lseek	19
#define	SYS_ult_getpid	20
#define	SYS_ult_mount	21
#define	SYS_ult_umount	22
				/* 23 is obsolete setuid */
#define	SYS_ult_getuid	24
				/* 25 is obsolete stime */
#define	SYS_ult_ptrace	26
				/* 27 is obsolete alarm */
				/* 28 is obsolete fstat */
				/* 29 is obsolete pause */
				/* 30 is obsolete utime */
				/* 31 is obsolete stty */
				/* 32 is obsolete gtty */
#define	SYS_ult_access	33
				/* 34 is obsolete nice */
				/* 35 is obsolete ftime */
#define	SYS_ult_sync	36
#define	SYS_ult_kill	37
#define	SYS_ult_stat	38
				/* 39 is obsolete setpgrp */
#define	SYS_ult_lstat	40
#define	SYS_ult_dup	41
#define	SYS_ult_pipe	42
				/* 43 is obsolete times */
#define	SYS_ult_profil	44
				/* 46 is obsolete setgid */
#define	SYS_ult_getgid	47
				/* 48 is obsolete sig */
#define	SYS_ult_acct	51
				/* 52 is obsolete phys */
				/* 53 is obsolete syslock */
#define	SYS_ult_ioctl	54
#define	SYS_ult_reboot	55
				/* 56 is obsolete mpxchan */
#define	SYS_ult_symlink	57
#define	SYS_ult_readlink	58
#define	SYS_ult_execve	59
#define	SYS_ult_umask	60
#define	SYS_ult_chroot	61
#define	SYS_ult_fstat	62
#define	SYS_ult_getpagesize	64
#define	SYS_ult_mremap	65
#define	SYS_ult_vfork	66
				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */
#define	SYS_ult_sbrk	69
#define	SYS_ult_sstk	70
#define	SYS_ult_mmap	71
#define	SYS_ult_vadvise	72
#define	SYS_ult_munmap	73
#define	SYS_ult_mprotect	74
#define	SYS_ult_madvise	75
#define	SYS_ult_vhangup	76
				/* 77 is obsolete vlimit */
#define	SYS_ult_mincore	78
#define	SYS_ult_getgroups	79
#define	SYS_ult_setgroups	80
#define	SYS_ult_getpgrp	81
#define	SYS_ult_setpgrp	82
#define	SYS_ult_setitimer	83
#define	SYS_ult_wait3	84
#define	SYS_ult_swapon	85
#define	SYS_ult_getitimer	86
#define	SYS_ult_gethostname	87
#define	SYS_ult_sethostname	88
#define	SYS_ult_getdtablesize	89
#define	SYS_ult_dup2	90
				/* 91 is obsolete getdopt ?? */
#define	SYS_ult_fcntl	92
#define	SYS_ult_select	93
				/* 94 is obsolete setdopt ?? */
#define	SYS_ult_fsync	95
#define	SYS_ult_setpriority	96
#define	SYS_ult_socket	97
#define	SYS_ult_connect	98
#define	SYS_ult_accept	99
#define	SYS_ult_getpriority	100
#define	SYS_ult_send	101
#define	SYS_ult_recv	102
#define	SYS_ult_sigreturn	103
#define	SYS_ult_bind	104
#define	SYS_ult_setsockopt	105
#define	SYS_ult_listen	106
				/* 107 is obsolete vtimes */
#define	SYS_ult_sigvec	108
#define	SYS_ult_sigblock	109
#define	SYS_ult_sigsetmask	110
#define	SYS_ult_sigpause	111
#define	SYS_ult_sigstack	112
#define	SYS_ult_recvmsg	113
#define	SYS_ult_sendmsg	114
				/* 115 is obsolete vtrace */
#define	SYS_ult_gettimeofday	116
#define	SYS_ult_getrusage	117
#define	SYS_ult_getsockopt	118
				/* 119 is obsolete resuba */
#define	SYS_ult_readv	120
#define	SYS_ult_writev	121
#define	SYS_ult_settimeofday	122
#define	SYS_ult_fchown	123
#define	SYS_ult_fchmod	124
#define	SYS_ult_recvfrom	125
#define	SYS_ult_setreuid	126
#define	SYS_ult_setregid	127
#define	SYS_ult_rename	128
#define	SYS_ult_truncate	129
#define	SYS_ult_ftruncate	130
#define	SYS_ult_flock	131
#define	SYS_ult_sendto	133
#define	SYS_ult_shutdown	134
#define	SYS_ult_socketpair	135
#define	SYS_ult_mkdir	136
#define	SYS_ult_rmdir	137
#define	SYS_ult_utimes	138
#define	SYS_alt_ult_sigreturn	139	/* 139 is alternate sigreturn */
#define	SYS_ult_adjtime	140
#define	SYS_ult_getpeername	141
#define	SYS_ult_gethostid	142
#define	SYS_ult_sethostid	143
#define	SYS_ult_getrlimit	144
#define	SYS_ult_setrlimit	145
#define	SYS_ult_killpg	146
#define	SYS_ult_quota	148
#define	SYS_ult_qquota	149
#define	SYS_ult_getsockname	150
#define	SYS_ult_sysmips	151
#define	SYS_ult_cacheflush	152
				/* 153 is obsolete cachectl */
#define	SYS_ult_atomic_op	155
				/* 157 is obsolete nfs_mount */
#define	SYS_ult_nfs_svc	158
#define	SYS_ult_getdirentries	159
				/* 160 is obsolete statfs */
				/* 161 is obsolete fstatfs */
				/* 162 is obsolete unmount */
#define	SYS_ult_async_daemon	163
#define	SYS_ult_getfh	164
#define	SYS_ult_getdomainname	165
#define	SYS_ult_setdomainname	166
				/* 167 is obsolete pcfs_mount */
				/* 168 is obsolete quotactl */
#define	SYS_ult_exportfs	169
				/* 170 is obsolete mount */
				/* 171 is obsolete mipshwconf */
#define	SYS_ult_msgctl	172
#define	SYS_ult_msgget	173
#define	SYS_ult_msgrcv	174
#define	SYS_ult_msgsnd	175
#define	SYS_ult_semctl	176
#define	SYS_ult_semget	177
#define	SYS_ult_semop	178
#define	SYS_ult_uname	179
#define	SYS_ult_shmsys	180
#define	SYS_ult_plock	181
				/* 182 is obsolete lockf */
				/* 183 is obsolete ustat */
#define	SYS_ult_getmnt	184
				/* 185 is obsolete mount */
				/* 186 is obsolete umount */
#define	SYS_ult_sigpending	187
#define	SYS_ult_setsid	188
#define	SYS_ult_waitpid	189
#define	SYS_ult_utc_gettime	233
#define	SYS_ult_utc_adjtime	234
				/* 252 is obsolete audcntl */
				/* 253 is obsolete audgen */
				/* 254 is obsolete startcpu */
				/* 255 is obsolete stopcpu */
#define	SYS_ult_getsysinfo	256
#define	SYS_ult_setsysinfo	257

#define	ult_FIRST	0
#define	ult_LAST	257

#endif	/* _SYS_ULT_SYSCALL_H_ */
